const colorCapitalize: { [letter: string]: string } = {
  A: "tomato",
  B: "orange",
  C: "yellow",
  D: "green",
  E: "cyan",
  F: "blue",
  G: "purple",
  H: "violet",
  I: "indigo",
  J: "aqua",
  K: "khaki",
  L: "lavender",
  M: "maroon",
  N: "navy",
  O: "olive",
  P: "pink",
  Q: "coral",
  R: "red",
  S: "silver",
  T: "tan",
  U: "teal",
  V: "violet",
  W: "wheat",
  X: "coral",
  Y: "yellow",
  Z: "azure",
};

export { colorCapitalize }
